server:
  port: 8080

spring:
  application:
    name: gox
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:gox
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.zhengchalei.gox: debug 