server:
  port: 8080

spring:
  application:
    name: gox
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gox
    username: root
    password: root
  data:
    web:
      pageable:
        one-indexed-parameters: true

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR
  language: kotlin

sa-token:
  is-print: true
  token-name: token
  timeout: -1
  is-concurrent: false

logging:
  level:
    com.zhengchalei.gox: debug