server:
  port: 8080

spring:
  application:
    name: gox
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gox
    username: postgres
    password: postgres
  profiles:
    include: file, auth
  servlet:
    multipart:
      max-file-size: 10MB
  flyway:
    enabled: false
    fail-on-missing-locations: true
jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: warning
  language: kotlin
sa-token:
  is-print: true
  token-name: token
  timeout: -1
  is-concurrent: false

logging:
  level:
    com.zhengchalei.gox: debug